apiVersion: v2
name: csi-nebulon
description: Nebulon CSI Driver

type: application


version: 0.1.4

maintainers: 
  - name: Nebulon Support #todo
    email: info@nebulon.com #todo

icon: https://raw.githubusercontent.com/Nebulon/helm-charts/master/docs/Nebulon.svg

appVersion: 0.1.4

