apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nebulon-mirrored
provisioner: nebulon.csi.nebulon.com
reclaimPolicy: Delete # Delete (default) or Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true 
parameters:
  volumeProtection: "mirrored" # nonMirrored (default) or mirrored
  fsType: "ext4" # ext4 (default) or xfs