# This YAML file contains all RBAC objects that are necessary to run external
# CSI attacher.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-nebulon-attacher
  namespace: {{ .Release.Namespace }}
---
# Attacher must be able to work with PVs, nodes and VolumeAttachments
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-nebulon-external-attacher-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["csinodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["storage.k8s.io"]
    resources: ["volumeattachments"]
    verbs: ["get", "list", "watch", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-nebulon-attacher-role
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: csi-nebulon-attacher
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: csi-nebulon-external-attacher-runner
  apiGroup: rbac.authorization.k8s.io

---
# Attacher must be able to work with configmaps or leases in the current namespace
# if (and only if) leadership election is enabled
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-nebulon-external-attacher-cfg
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-nebulon-attacher-role-cfg
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: csi-nebulon-attacher
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: csi-nebulon-external-attacher-cfg
  apiGroup: rbac.authorization.k8s.io
