# This YAML file contains all RBAC objects that are necessary to run external
# CSI resizer.

apiVersion: v1
kind: ServiceAccount
metadata:
  name: csi-nebulon-resizer

---
# Resizer must be able to work with PVCs, PVs, SCs.
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nebulon-external-resizer-runner
rules:
  - apiGroups: [""]
    resources: ["persistentvolumes"]
    verbs: ["get", "list", "watch", "update", "patch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims/status"]
    verbs: ["update", "patch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["list", "watch", "create", "update", "patch"]

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-nebulon-resizer-role
subjects:
  - kind: ServiceAccount
    name: csi-nebulon-resizer
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: nebulon-external-resizer-runner
  apiGroup: rbac.authorization.k8s.io

---
# Resizer must be able to work with end point in current namespace
# if (and only if) leadership election is enabled
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nebulon-external-resizer-cfg
rules:
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "watch", "list", "delete", "update", "create"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-nebulon-resizer-role-cfg
subjects:
  - kind: ServiceAccount
    name: csi-nebulon-resizer
roleRef:
  kind: Role
  name: nebulon-external-resizer-cfg
  apiGroup: rbac.authorization.k8s.io
