kind: Service
apiVersion: v1
metadata:
  name: csi-nebulon-resizer
  labels:
    app: csi-nebulon-resizer
spec:
  selector:
    app: csi-nebulon-resizer
  ports:
    - name: dummy
      port: 12345

---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: csi-nebulon-resizer
  labels:
    csi-nebulon: "true"
spec:
  serviceName: "csi-nebulon-resizer"
  replicas: 1
  selector:
    matchLabels:
      app: csi-nebulon-resizer
  template:
    metadata:
      labels:
        app: csi-nebulon-resizer
        csi-nebulon: "true"
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - csi-nebulon-plugin
            topologyKey: kubernetes.io/hostname
      serviceAccountName: csi-nebulon-resizer
      containers:
        - name: csi-nebulon-resizer
          image: quay.io/k8scsi/csi-resizer:v0.3.0
          args:
            - -v=5
            - -csi-address=/csi/csi.sock
          volumeMounts:
            - mountPath: /csi
              name: socket-dir
      volumes:
        - hostPath:
            path: "{{ .Values.kubelet.path }}/plugins/csi-nebulon"
            type: DirectoryOrCreate
          name: socket-dir
