{{ if .Values.storageclass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ .Values.storageclass.default }}"
provisioner: csi.nebulon.com
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: false
{{ end }}
