{{ if .Values.storageclass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageclass.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: "{{ .Values.storageclass.default }}"
provisioner: {{ .Values.driver.name }}
reclaimPolicy: Delete
volumeBindingMode: Immediate
allowVolumeExpansion: {{ .Values.storageclass.allowexpansion }}
{{ end }}
